## --------------------------------------------- ##
#          NEON Storage Flux Metadata -----
## --------------------------------------------- ##
# Purpose:
# Create a single metadata/data-dictionary CSV for the site-level storage flux
# files produced by `workflows/flow.neon.storage.R`.
#
# Output:
#   /Volumes/MaloneLab/Research/FluxGradient/NEON_Storage_Flux/
#     NEON_storage_flux_metadata.csv
#
# Optional command-line use:
#   Rscript workflows/flow.neon.storage.metadata.R [storage_dir]

storage_dir <- "/Volumes/MaloneLab/Research/FluxGradient/NEON_Storage_Flux"

args <- commandArgs(trailingOnly = TRUE)
if (length(args) >= 1) {
  storage_dir <- args[[1]]
}

metadata_out <- file.path(storage_dir, "NEON_storage_flux_metadata.csv")

metadata <- data.frame(
  column_name = c(
    "site",
    "gas",
    "time_halfhour",
    "timeMid",
    "timeBgn",
    "timeEnd",
    "time_halfhour_storage_end",
    "pressure_kPa",
    "tair_C",
    "rh_pct",
    "water_vapor_pressure_kPa",
    "dry_air_molar_density_molm3",
    "dry_air_concentration",
    "dry_air_concentration_uncertainty",
    "concentration_units",
    "time_sync_offset_s",
    "time_synchronization_source",
    "TimeTube_s",
    "tube_time_source",
    "bottom_height_m",
    "top_height_m",
    "column_height_m",
    "n_levels_total",
    "n_levels_used",
    "n_density_levels",
    "max_interpolation_gap_s",
    "vertical_grid_cells",
    "storage_qf",
    "qf_reason",
    "column_burden",
    "burden_units",
    "dt_s",
    "storage_flux_column_rate",
    "storage_flux",
    "storage_flux_uncertainty",
    "storage_flux_uncertainty_units",
    "storage_flux_uncertainty_method",
    "storage_source_n",
    "storage_flux_ameriflux_sign",
    "units",
    "storage_source_column",
    "storage_value_source",
    "storage_framework",
    "storage_method",
    "time_synchronization_method",
    "time_interpolation_method",
    "rate_calculation_method",
    "vertical_interpolation_method",
    "minimum_valid_levels",
    "site_tower_metadata_source",
    "molar_density_method",
    "density_correction",
    "storage_flux_sign_convention",
    "storage_flux_time_convention",
    "storage_time_row_inserted",
    "storage_flux_filled",
    "storage_flux_filled_uncertainty",
    "storage_flux_is_gapfilled",
    "storage_gapfill_method",
    "storage_gapfill_n_donor",
    "storage_flux_ameriflux_sign_filled"
  ),
  data_type = c(
    "character",
    "character",
    "datetime_UTC",
    "datetime_UTC",
    "datetime_UTC",
    "datetime_UTC",
    "datetime_UTC",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "character",
    "numeric",
    "character",
    "numeric",
    "character",
    "numeric",
    "numeric",
    "numeric",
    "integer",
    "integer",
    "integer",
    "numeric",
    "integer",
    "integer",
    "character",
    "numeric",
    "character",
    "numeric",
    "numeric",
    "numeric",
    "numeric",
    "character",
    "character",
    "integer",
    "numeric",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "character",
    "integer",
    "character",
    "character",
    "character",
    "character",
    "character",
    "logical",
    "numeric",
    "numeric",
    "logical",
    "character",
    "integer",
    "numeric"
  ),
  units = c(
    "NEON site code",
    "CO2, H2O, or CH4",
    "UTC",
    "UTC",
    "UTC",
    "UTC",
    "UTC",
    "kPa",
    "deg C",
    "percent",
    "kPa",
    "mol dry air m-3",
    "gas-specific concentration_units",
    "gas-specific concentration_units",
    "text",
    "s",
    "text",
    "s",
    "text",
    "m",
    "m",
    "m",
    "count",
    "count",
    "count",
    "s",
    "count",
    "0 good, 1 bad",
    "text",
    "gas-specific burden_units",
    "text",
    "s",
    "gas-specific units",
    "gas-specific units",
    "gas-specific units",
    "text",
    "text",
    "count",
    "gas-specific units",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "text",
    "count",
    "text",
    "text",
    "text",
    "text",
    "text",
    "TRUE/FALSE",
    "gas-specific units",
    "gas-specific units",
    "TRUE/FALSE",
    "text",
    "count",
    "gas-specific units"
  ),
  description = c(
    "Four-character NEON site identifier.",
    "Gas or storage-flux target represented by the row.",
    "Primary 30-minute timestamp used for joins and plotting.",
    "Timestamp label used by the storage output. For computed CH4 this labels the interval start.",
    "Beginning timestamp of the storage calculation interval or source interval.",
    "Ending timestamp of the storage calculation interval or source interval.",
    "Interval-end timestamp retained for storage terms whose primary label is interval start.",
    "Mean atmospheric pressure used for profile density correction when available.",
    "Mean air temperature used for profile density correction when available.",
    "Mean relative humidity used to estimate water vapor pressure when available.",
    "Water vapor pressure estimated from RH and saturation vapor pressure.",
    "Dry-air molar density calculated as (P - e) / (R * T).",
    "Dry-air gas concentration used in storage calculation.",
    "Standard uncertainty of dry-air gas concentration propagated from input variance and sample count.",
    "Units for dry_air_concentration and dry_air_concentration_uncertainty.",
    "Applied time synchronization offset relative to original timeMid.",
    "Source of time synchronization information.",
    "Tube transit-time correction from site tower metadata where available.",
    "Source or availability flag for TimeTube_s.",
    "Lowest tower-profile measurement height used for storage context.",
    "Highest tower-profile measurement height used for storage context.",
    "Tower-column height used for storage integration context.",
    "Total number of tower levels in site metadata.",
    "Number of tower levels contributing valid gas concentration or rate information at the half-hour.",
    "Number of tower levels with valid dry-air molar density information at the half-hour.",
    "Largest temporal interpolation gap among tower levels for the half-hour.",
    "Number of vertical grid cells used in the eddy4R-style spatial interpolation.",
    "Storage quality flag. One indicates the raw storage estimate should not be used directly.",
    "Reason for storage_qf value.",
    "Vertically integrated column burden. Currently retained for compatibility and may be NA.",
    "Units for column_burden.",
    "Time step used for storage-rate calculation.",
    "Column-rate storage flux from the raw calculation or pulled source when directly comparable.",
    "Raw storage flux value before gapfilling. CO2 and H2O may be pulled directly from NEON aligned storage columns; CH4 is computed.",
    "Standard uncertainty for storage_flux where available.",
    "Units for storage_flux_uncertainty.",
    "Method used to estimate storage_flux_uncertainty.",
    "Number of source storage values aggregated into a half-hour for pulled NEON storage terms.",
    "Sign-flipped storage_flux helper for AmeriFlux-style storage comparisons for CO2 and CH4.",
    "Units for storage_flux and storage_flux_column_rate.",
    "Original aligned-file column used as the source storage term, when storage was pulled rather than computed.",
    "Human-readable description of whether storage was pulled from NEON aligned output or computed from profiles.",
    "Storage framework or compatibility implementation used by the script.",
    "Storage calculation method summary.",
    "Time synchronization method summary.",
    "Time interpolation method summary.",
    "Rate calculation method summary.",
    "Vertical interpolation and integration method summary.",
    "Minimum number of valid tower levels required before raw computed storage is accepted.",
    "Path or description of tower metadata source used to determine tower levels and heights.",
    "Dry-air molar density calculation method.",
    "Description of dry-air density correction.",
    "Sign convention note for storage_flux and storage_flux_ameriflux_sign.",
    "Timestamp convention note for storage_flux.",
    "TRUE when the row was inserted only to complete the 30-minute time grid.",
    "Gapfilled continuous storage-flux series. This is the preferred complete series for downstream use.",
    "Uncertainty assigned to storage_flux_filled, inherited or gapfill-derived.",
    "TRUE when storage_flux_filled replaces a missing raw storage_flux value.",
    "Method used to fill storage_flux_filled.",
    "Number of donor observations used by the gapfill method.",
    "Sign-flipped helper for storage_flux_filled for AmeriFlux-style comparisons for CO2 and CH4."
  ),
  source = c(
    "file/site metadata",
    "script",
    "script",
    "script",
    "input or script",
    "input or script",
    "script",
    "NEON aligned concentrations",
    "NEON aligned concentrations",
    "NEON aligned concentrations",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "NEON attributes",
    "script",
    "NEON attributes",
    "NEON attributes",
    "NEON attributes",
    "NEON attributes",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "reserved",
    "script",
    "script",
    "script",
    "script or NEON aligned storage",
    "script",
    "script",
    "script",
    "NEON aligned storage aggregation",
    "script",
    "script",
    "NEON aligned concentrations",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "NEON attributes",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script",
    "script"
  ),
  notes = c(
    "",
    "CO2 storage_flux is FC_stor_interp; H2O storage_flux is LE_stor_interp; CH4 storage_flux is computed.",
    "CSV timestamps are written as YYYY-MM-DD HH:MM:SS in UTC.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Derived from RH and air temperature.",
    "Uses water-vapor pressure correction.",
    "Gas-specific concentration scale: CO2 umol m-3, H2O mmol m-3, CH4 nmol m-3.",
    "Computed from input vari_A/B and numSamp_A/B where available.",
    "",
    "Includes gas offset and tube-time correction where available.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Applies only to computed profile-based storage; pulled storage rows may be NA.",
    "",
    "",
    "Currently not populated in the output.",
    "",
    "Typically 1800 s.",
    "For H2O pulled as latent heat storage, this may be NA because units are W m-2.",
    "Use storage_flux_filled for continuous downstream calculations.",
    "",
    "",
    "",
    "Mostly populated for pulled CO2/H2O storage rows.",
    "Use only for AmeriFlux comparison; not for NEON-native totals.",
    "CO2 umol m-2 s-1; H2O W m-2 for pulled LE storage; CH4 nmol m-2 s-1.",
    "FC_stor_interp for CO2; LE_stor_interp for H2O; NA for computed CH4.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "NEON-native convention adds storage to turbulent flux.",
    "",
    "Inserted rows allow every missing half-hour to appear explicitly in the CSV.",
    "Gapfill order: short linear interpolation, +/-30 day diurnal median, diurnal climatology, site/gas median.",
    "",
    "",
    "",
    "",
    "Use only for AmeriFlux comparison; not for NEON-native totals."
  ),
  stringsAsFactors = FALSE
)

csv_files <- list.files(storage_dir, pattern = "_storage_flux[.]csv$", full.names = TRUE)

if (length(csv_files) > 0) {
  sample_cols <- names(utils::read.csv(csv_files[[1]], nrows = 1))
  missing_metadata <- setdiff(sample_cols, metadata$column_name)
  missing_output_cols <- setdiff(metadata$column_name, sample_cols)

  if (length(missing_metadata) > 0) {
    warning(
      "Metadata table does not document output columns: ",
      paste(missing_metadata, collapse = ", "),
      call. = FALSE
    )
  }

  if (length(missing_output_cols) > 0) {
    warning(
      "Metadata table documents columns not present in sample output: ",
      paste(missing_output_cols, collapse = ", "),
      call. = FALSE
    )
  }
}

utils::write.csv(metadata, metadata_out, row.names = FALSE, na = "")
message("Saved metadata table to ", metadata_out)
